traffic_dbt:
  outputs:
    dev:
      type: postgres
      threads: 10
      host: 127.0.0.1
      port: 5434
      user: eyaya
      pass: Nigielove_21
      dbname: open_trafic
      schema: trafic_schema

    prod:
      type: postgres
      threads: 10
      host: 127.0.0.1
      port: 5434
      user: eyaya
      pass: Nigielove_21
      dbname: open_trafic
      schema: trafic_schema

  target: prod
